### ISSUE TITLE
Downloading datasets from s3 requires credentials

### ISSUE THREAD

**Issue by mjdietzx** [wayaai/waya-dc#1]
Error when running `python3 wayadc/utils/get_datasets.py`:

```bash
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

Fix:

```bash
ubuntu@ip-172-31-13-115:~/waya-dc$ exit
logout
Connection to 52.55.215.188 closed.
Michaels-MacBook-Pro:Downloads mjdietzx$ scp -i aws-p2.pem -pr ~/.aws/ ubuntu@52.55.215.188:~/.aws/
```

**Comment by llj098** [comment]
Hi,do you have any plan to open the dataset? 

Thanks

**Comment by mjdietzx** [comment]
If using `get_datasets.py` to download data sets the script relies on `boto3` to download AWS S3 objects and you need to have AWS credentials set-up: http://boto3.readthedocs.io/en/latest/guide/quickstart.html#configuration.

Otherwise you can download manually from these public links:
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/dermnetnz-scraped.zip
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/howardzzh-clinical.zip
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/howardzzh.zip
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/isic-archive.zip
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/noisy-scrape.zip
- https://s3-us-west-1.amazonaws.com/waya-sig-ai/ph2-dataset.zip

**Comment by llj098** [comment]
Thanks @mjdietzx I am very appreciate.

**Comment by noahbishop** [comment]
Hi @mjdietzx, I get a NoSuchBucket error when using those links. Are there updated public links? I am trying to use them as part of a small research work. (I am a student)

**Comment by mjdietzx** [comment]
@noahbishop I have removed data sets. The data sets are all open but I don't have the rights to redistribute them. I will update the README to link to the data sets instead where you will have to get them yourself.

**Comment by noahbishop** [comment]
@mjdietzx I understand. Thank you!
